name: build

on:
  # Build file modifications
  push:
    branches: [ 'master' ]
    paths: [ '.github/workflows/build.yml', '.devops/**' ]
  #pull_request:
  #  branches: [ 'master' ]

  # Daily rebuild
  schedule:
    - cron: "0 4 * * *"

  # Manual rebuild, in case of some important upstream change
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ssl: [nossl, ssl]
        avx: [noavx, avx, avx2, avx512]
        include:
          - ssl: nossl
            ssl_defines: ''
          - ssl: ssl
            ssl_defines: '-DLLAMA_SERVER_SSL=ON -DOPENSSL_USE_STATIC_LIBS=ON'
          - avx: noavx
            avx_defines: '-DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_FMA=OFF'
          - avx: avx
            avx_defines: '-DLLAMA_AVX2=OFF'
          - avx: avx2
            avx_defines: ''
          - avx: avx512
            avx_defines: '-DLLAMA_AVX512=ON'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout llama.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/llama.cpp
          path: repo

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Setup Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          packages: build-base cmake ccache git openssl-dev openssl-libs-static

      - name: CMake
        run: |
          mkdir repo/build
          cd repo/build
          cmake .. -DLLAMA_NATIVE=OFF -DLLAMA_STATIC=ON -DLLAMA_BUILD_SERVER=ON -DCMAKE_BUILD_TYPE=Release ${{ matrix.ssl_defines }} ${{ matrix.avx_defines }}
          cmake --build . --config Release --target server -j ${{ steps.cpu-cores.outputs.count }}
          strip bin/server
        shell: alpine.sh {0}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ matrix.ssl }}-${{ matrix.avx }}
          path: repo/build/bin/server
          if-no-files-found: error

      - name: Build and push Docker image
        uses: macbre/push-to-ghcr@v13
        with:
          dockerfile: .devops/server.Dockerfile
          context: repo/build/bin
          image_name: ${{ github.repository }}
          image_tag: server-${{ matrix.ssl }}-${{ matrix.avx }}
          github_token: ${{ secrets.GHCR_ACCESS_TOKEN }}
          docker_io_user: ${{ env.DOCKER_IO_USER }}
          docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}

